require 'bundler'
require 'bundler/cli'
require 'bundler/cli/exec'

require_relative 'lib/redux/version'

task :push_ruby_packages do
  Rake::Task['push_ruby_packages_to_rubygems'].invoke
  Rake::Task['push_ruby_packages_to_isomorfeus'].invoke
  Rake::Task['push_ruby_packages_to_github'].invoke
end

task :push_ruby_packages_to_rubygems do
  system("gem push isomorfeus-redux-#{Redux::VERSION}.gem")
end

task :push_ruby_packages_to_github do
  system("gem push --key github --host https://rubygems.pkg.github.com/isomorfeus isomorfeus-redux-#{Redux::VERSION}.gem")
end

task :push_ruby_packages_to_isomorfeus do
  Bundler.with_original_env do
    system("scp isomorfeus-redux-#{Redux::VERSION}.gem iso:~/gems/")
    system("ssh iso \"bash -l -c 'gem inabox gems/isomorfeus-redux-#{Redux::VERSION}.gem --host http://localhost:5555/'\"")
  end
end
